# Generated by Django 2.2.8 on 2019-12-20 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_signature', models.ImageField(default='export/uploads/signbox.png', help_text='Please upload a PNG file with dimensions 250x150\nA blank signature requires the upload of a white .png', upload_to='export/uploads')),
                ('login_failure_limit', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('se_help_text', models.CharField(default='Service', max_length=50, verbose_name='Service Help Text')),
                ('at_help_text', models.CharField(default='Athletics', max_length=30, verbose_name='Athletics Help Text')),
                ('fa_help_text', models.CharField(default='Fine Arts', max_length=30, verbose_name='Fine Arts Help Text')),
            ],
        ),
    ]
