# Generated by Django 2.2.5 on 2019-10-04 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='login_failure_limit',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='principal_signature',
            field=models.ImageField(default='export/uploads/no-img.png', upload_to='export/uploads'),
        ),
    ]
