# Generated by Django 2.2.9 on 2020-01-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='at_help_text',
            field=models.CharField(default='Athletics', max_length=100, verbose_name='Athletics Help Text'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='fa_help_text',
            field=models.CharField(default='Fine Arts', max_length=100, verbose_name='Fine Arts Help Text'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='se_help_text',
            field=models.CharField(default='Service', max_length=100, verbose_name='Service Help Text'),
        ),
    ]
