# Generated by Django 2.2.9 on 2020-03-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20200129_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='principal_signature',
            field=models.ImageField(default='export/uploads/signbox.png', help_text='Please upload a PNG file with dimensions 500 x 250\nA blank signature requires the upload of a white .png', upload_to='export/uploads'),
        ),
    ]
