# Generated by Django 2.2.5 on 2019-10-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20191004_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='athletics_help_text',
            field=models.TextField(default='Notes for Athletics', max_length=100),
        ),
        migrations.AddField(
            model_name='configuration',
            name='fine_arts_help_text',
            field=models.TextField(default='Notes for Fine Arts', max_length=100),
        ),
        migrations.AddField(
            model_name='configuration',
            name='service_help_text',
            field=models.TextField(default='Notes for Service', max_length=100),
        ),
    ]
