# Generated by Django 2.2.5 on 2019-10-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20191004_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='athletics_help_text',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='fine_arts_help_text',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='service_help_text',
        ),
        migrations.AddField(
            model_name='configuration',
            name='at_help_text',
            field=models.CharField(default='Athletics', max_length=30, verbose_name='Athletics Help Text'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='fa_help_text',
            field=models.CharField(default='Fine Arts', max_length=30, verbose_name='Fine Arts Help Text'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='se_help_text',
            field=models.CharField(default='Service', max_length=50, verbose_name='Service Help Text'),
        ),
    ]
