# Generated by Django 2.2.5 on 2019-10-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_auto_20191004_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='principal_signature',
            field=models.ImageField(default='export/uploads/signbox.png', help_text='Please upload a PNG file with dimensions 250x100', upload_to='export/uploads'),
        ),
    ]
