# Generated by Django 2.2.7 on 2019-12-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_auto_20191023_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='principal_signature',
            field=models.ImageField(default='export/uploads/signbox.png', help_text='Please upload a PNG file with dimensions 250x100\nA blank signature requires the upload of a white .png', upload_to='export/uploads'),
        ),
    ]
