# Generated by Django 2.2.8 on 2019-12-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_merge_20191205_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='principal_signature',
            field=models.ImageField(default='export/uploads/signbox.png', help_text='Please upload a PNG file with dimensions 250x150\nA blank signature requires the upload of a white .png', upload_to='export/uploads'),
        ),
    ]
