# Generated by Django 2.2.13 on 2021-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Set Description', max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='can_upload',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='can_view',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='no_entry',
        ),
        migrations.AddField(
            model_name='customuser',
            name='permissions',
            field=models.ManyToManyField(to='users.AccessControl'),
        ),
    ]
