# Generated by Django 2.1.2 on 2019-06-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='autofocus',
            field=models.IntegerField(choices=[(1, 'Service'), (2, 'Athletics'), (3, 'Fine Arts'), (4, 'Scholar T1'), (5, 'Scholar T2')], default=1),
        ),
    ]
