# Generated by Django 2.2.8 on 2019-12-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='text_colour',
            field=models.CharField(default='#ADD8E6', max_length=7),
        ),
    ]
