# Generated by Django 2.2.13 on 2021-05-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210506_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontrol',
            name='identifier',
            field=models.CharField(default='Set Identifier', max_length=250),
        ),
    ]
