# Generated by Django 2.2.5 on 2019-09-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_no_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view',
            field=models.BooleanField(default=False, help_text='Designates whether the user can see the student view.', verbose_name='Can view student page'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='no_entry',
            field=models.BooleanField(default=False, help_text='Designates whether the user can enter data at the student view.', verbose_name='No entry at student page'),
        ),
    ]
