# Generated by Django 2.2.8 on 2019-12-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_text_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='collapsible_bar_colour',
            field=models.CharField(default='#eeeeee', max_length=7),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='alternate_row_colour',
            field=models.CharField(default='#7AD7F0', max_length=7),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='text_colour',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
