# Generated by Django 2.2.5 on 2019-09-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190923_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='can_view',
            field=models.BooleanField(default=False, help_text='Designates whether the user can see the student view. Note: If a user is a superuser, this is disregarded.', verbose_name='Can view student page'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='no_entry',
            field=models.BooleanField(default=True, help_text='Designates whether the user can enter data at the student view. Note: If a user is a superuser, this is disregarded.', verbose_name='No entry at student page'),
        ),
    ]
