# Generated by Django 2.2.13 on 2021-05-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210506_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrol',
            name='identifier',
            field=models.CharField(default='Set Identifier', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='accesscontrol',
            field=models.ManyToManyField(blank=True, help_text='Specify access control for this user. Ctrl + A to select all.', related_name='accesscontrol_set', related_query_name='accesscontrol', to='users.AccessControl', verbose_name='Database Access Control'),
        ),
    ]
