# Generated by Django 2.2.5 on 2019-10-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20190928_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_upload',
            field=models.BooleanField(default=False, help_text='Designates whether the user can submit files for at direct entry pages. Note: If a user is a superuser, this is disregarded.', verbose_name='Upload at Direct'),
        ),
    ]
