# Generated by Django 2.2.5 on 2019-10-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_can_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='header_colour',
            field=models.CharField(default='#ADD8E6', max_length=7),
        ),
        migrations.AddField(
            model_name='customuser',
            name='page_colour',
            field=models.CharField(default='#ADD8E6', max_length=7),
        ),
    ]
