# Generated by Django 2.2.7 on 2019-11-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191023_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='can_upload',
            field=models.BooleanField(default=False, help_text='Designates whether the user can submit files for at direct entry pages. Note: If a user is a superuser, this is disregarded.', verbose_name='Bulk upload at Direct Entry'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='can_view',
            field=models.BooleanField(default=False, help_text='Designates whether the user can see the student view with all the data. Note: If a user is a superuser, this is disregarded.', verbose_name='Can view student page with all information'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='no_entry',
            field=models.BooleanField(default=True, help_text='Designates whether the user can enter data at the student view. Note: If a user is a superuser, this is disregarded.', verbose_name='Disable entry at student page'),
        ),
    ]
