# Generated by Django 2.2.7 on 2019-11-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191126_1606'),
        ('users', '0008_auto_20191127_1536'),
    ]

    operations = [
    ]
