# Generated by Django 2.2.7 on 2019-12-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191205_1158'),
        ('users', '0009_merge_20191128_0025'),
    ]

    operations = [
    ]
