# Generated by Django 2.2.7 on 2019-12-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20191205_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alternate_row_colour',
            field=models.CharField(default='#ADD8E6', max_length=7),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_firstvisit',
            field=models.BooleanField(default=True),
        ),
    ]
