# Generated by Django 2.2.7 on 2019-12-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191214_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_firstvisit',
            new_name='first_visit',
        ),
    ]
