language: python
python:
  - "3.7"
  - "3.8"

services:
  - mysql

env:
  - DJANGO=2.2.9 DB=mysql

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'CREATE DATABASE PGDB;'
  - mysql -e "CREATE USER 'pgadmin'@'localhost' IDENTIFIED BY '2.71828';"
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'pgadmin'@'localhost';"

script:
  - python manage.py migrate
  - python manage.py test
  - python manage.py check