# Generated by Django 2.2.3 on 2019-07-13 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField()),
                ('start_year', models.SmallIntegerField()),
                ('anecdote', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PlistCutoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019)),
                ('grade_8_T1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_8_T2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_9_T1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_9_T2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_10_T1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_10_T2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_11_T1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_11_T2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_12_T1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_12_T2', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
            options={
                'verbose_name': 'Principal List Cutoff',
                'verbose_name_plural': 'Principal List Cutoffs',
            },
        ),
        migrations.CreateModel(
            name='PointCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=2)),
                ('code', models.SmallIntegerField()),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30, verbose_name='First Name')),
                ('last', models.CharField(max_length=30, verbose_name='Last Name')),
                ('legal', models.CharField(max_length=30, verbose_name='Legal Name')),
                ('student_num', models.PositiveIntegerField(verbose_name='Student Number')),
                ('homeroom', models.CharField(max_length=3, verbose_name='Homeroom')),
                ('sex', models.CharField(max_length=1, verbose_name='Sex')),
                ('grad_year', models.IntegerField()),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term1', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('term2', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Grade')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PointCodes')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Student'),
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.BooleanField()),
                ('athletics', models.BooleanField()),
                ('honour', models.BooleanField()),
                ('p_list', models.BooleanField()),
                ('fine_arts', models.BooleanField()),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silver_pin', models.DateField()),
                ('gold_pin', models.DateField()),
                ('gold_plus', models.DateField()),
                ('platinum_pin', models.DateField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Student')),
            ],
        ),
    ]
