# Generated by Django 2.2.8 on 2020-01-16 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField()),
                ('start_year', models.SmallIntegerField()),
                ('anecdote', models.CharField(blank=True, max_length=300)),
                ('_term1_avg', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('_term2_avg', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('term1_GE', models.BooleanField(default=False)),
                ('term2_GE', models.BooleanField(default=False)),
                ('isnull_term1', models.BooleanField(default=False)),
                ('isnull_term2', models.BooleanField(default=False)),
                ('isnull_SE', models.BooleanField(default=False)),
                ('isnull_AT', models.BooleanField(default=False)),
                ('isnull_FA', models.BooleanField(default=False)),
                ('isnull_SC', models.BooleanField(default=False)),
                ('SE_total', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('AT_total', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('FA_total', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('SC_total', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PlistCutoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1984, '1984 → 1985'), (1985, '1985 → 1986'), (1986, '1986 → 1987'), (1987, '1987 → 1988'), (1988, '1988 → 1989'), (1989, '1989 → 1990'), (1990, '1990 → 1991'), (1991, '1991 → 1992'), (1992, '1992 → 1993'), (1993, '1993 → 1994'), (1994, '1994 → 1995'), (1995, '1995 → 1996'), (1996, '1996 → 1997'), (1997, '1997 → 1998'), (1998, '1998 → 1999'), (1999, '1999 → 2000'), (2000, '2000 → 2001'), (2001, '2001 → 2002'), (2002, '2002 → 2003'), (2003, '2003 → 2004'), (2004, '2004 → 2005'), (2005, '2005 → 2006'), (2006, '2006 → 2007'), (2007, '2007 → 2008'), (2008, '2008 → 2009'), (2009, '2009 → 2010'), (2010, '2010 → 2011'), (2011, '2011 → 2012'), (2012, '2012 → 2013'), (2013, '2013 → 2014'), (2014, '2014 → 2015'), (2015, '2015 → 2016'), (2016, '2016 → 2017'), (2017, '2017 → 2018'), (2018, '2018 → 2019'), (2019, '2019 → 2020'), (2020, '2020 → 2021')], default=2020, unique=True)),
                ('grade_8_T1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_8_T2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_9_T1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_9_T2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_10_T1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_10_T2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_11_T1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_11_T2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_12_T1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade_12_T2', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
            options={
                'verbose_name': 'Principal List Cutoff',
                'verbose_name_plural': 'Principal List Cutoffs',
            },
        ),
        migrations.CreateModel(
            name='PointCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=2)),
                ('code', models.SmallIntegerField()),
                ('description', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['catagory', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30, verbose_name='First Name')),
                ('last', models.CharField(max_length=30, verbose_name='Last Name')),
                ('legal', models.CharField(max_length=30, verbose_name='Legal Name')),
                ('sex', models.CharField(help_text='This field accepts any letter of the alphabet', max_length=1, verbose_name='Sex')),
                ('student_num', models.PositiveIntegerField(help_text='This number must be unique as it is used to identify students', unique=True, verbose_name='Student Number')),
                ('grad_year', models.IntegerField(help_text='Year of Graduation', verbose_name='Grad Year')),
                ('cur_grade_num', models.IntegerField(verbose_name='current grade')),
                ('homeroom_str', models.CharField(default='#', max_length=15, verbose_name='Homeroom letter')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_modified', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['last', 'first'],
            },
        ),
        migrations.CreateModel(
            name='Grade_10',
            fields=[
                ('grade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Grade')),
            ],
            bases=('data.grade',),
        ),
        migrations.CreateModel(
            name='Grade_11',
            fields=[
                ('grade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Grade')),
            ],
            bases=('data.grade',),
        ),
        migrations.CreateModel(
            name='Grade_12',
            fields=[
                ('grade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Grade')),
            ],
            bases=('data.grade',),
        ),
        migrations.CreateModel(
            name='Grade_8',
            fields=[
                ('grade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Grade')),
            ],
            bases=('data.grade',),
        ),
        migrations.CreateModel(
            name='Grade_9',
            fields=[
                ('grade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Grade')),
            ],
            bases=('data.grade',),
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Grade')),
            ],
        ),
    ]
