# Generated by Django 2.2.4 on 2019-09-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grad_year',
            field=models.IntegerField(help_text='Year of Graduation', verbose_name='Grad Year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='homeroom',
            field=models.CharField(help_text='Do not change unless you know what you are doing', max_length=15, verbose_name='Homeroom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(help_text='This field accepts any letter of the alphabet', max_length=1, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_num',
            field=models.PositiveIntegerField(help_text='This number must be unique as it is used to identify students', verbose_name='Student Number'),
        ),
    ]
