# Generated by Django 2.0.5 on 2018-05-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silver_pin', models.DateField()),
                ('gold_pin', models.DateField()),
                ('gold_plus', models.DateField()),
                ('platinum_pin', models.DateField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.BooleanField()),
                ('athletics', models.BooleanField()),
                ('honour', models.BooleanField()),
                ('p_list', models.BooleanField()),
                ('fine_arts', models.BooleanField()),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='PointCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
                ('code', models.SmallIntegerField()),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
                ('code', models.SmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term1', models.DecimalField(decimal_places=5, max_digits=7)),
                ('term2', models.DecimalField(decimal_places=5, max_digits=7)),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Grade')),
            ],
        ),
    ]
