# Generated by Django 2.2.8 on 2019-12-20 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='points',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PointCodes'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_10',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Grade_10'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_11',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Grade_11'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_12',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Grade_12'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_8',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Grade_8'),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_9',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Grade_9'),
        ),
    ]
