# Generated by Django 2.2.9 on 2020-01-29 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200116_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 8, 4, 33, 496681, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True, help_text='Designates whether this student should be treated as active. Unselect this instead of deleting students.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='student',
            name='homeroom_str',
            field=models.CharField(default='#', max_length=15, verbose_name='Homeroom'),
        ),
    ]
