# Generated by Django 2.2.5 on 2019-09-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190910_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-grade']},
        ),
        migrations.AlterModelOptions(
            name='pointcodes',
            options={'ordering': ['catagory', 'code']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last', 'first']},
        ),
    ]
