# Generated by Django 2.2.7 on 2019-11-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20191128_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='homeroom_char',
        ),
        migrations.AddField(
            model_name='student',
            name='homeroom_str',
            field=models.CharField(default='#', max_length=15, verbose_name='Homeroom letter'),
        ),
    ]
