# Generated by Django 2.2.7 on 2019-11-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20191128_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bigblock_award',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='gold_pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='platinum_pin',
            field=models.BooleanField(default=False),
        ),
    ]
