# Generated by Django 2.0.5 on 2018-06-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20180621_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='AT_total',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='FA_total',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='SC_total',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='SE_total',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
