# Generated by Django 2.2.4 on 2019-09-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190928_1132'),
        ('data', '0003_auto_20190928_0029'),
    ]

    operations = [
    ]
