# Generated by Django 2.2.9 on 2020-03-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_loggedaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['active', 'last', 'first']},
        ),
        migrations.AlterField(
            model_name='plistcutoff',
            name='grade_10_T1',
            field=models.DecimalField(decimal_places=3, default=99.999, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plistcutoff',
            name='grade_10_T2',
            field=models.DecimalField(decimal_places=3, default=99.999, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plistcutoff',
            name='grade_11_T1',
            field=models.DecimalField(decimal_places=3, default=99.999, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plistcutoff',
            name='grade_11_T2',
            field=models.DecimalField(decimal_places=3, default=99.999, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plistcutoff',
            name='grade_12_T1',
            field=models.DecimalField(decimal_places=3, default=99.999, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plistcutoff',
            name='grade_12_T2',
            field=models.DecimalField(decimal_places=3, default=99.999, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plistcutoff',
            name='grade_8_T1',
            field=models.DecimalField(decimal_places=3, default=99.999, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plistcutoff',
            name='grade_8_T2',
            field=models.DecimalField(decimal_places=3, default=99.999, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plistcutoff',
            name='grade_9_T1',
            field=models.DecimalField(decimal_places=3, default=99.999, max_digits=5),
        ),
        migrations.AlterField(
            model_name='plistcutoff',
            name='grade_9_T2',
            field=models.DecimalField(decimal_places=3, default=99.999, max_digits=5),
        ),
    ]
