# Generated by Django 2.0.5 on 2018-06-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20180621_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='term1',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='term2',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
    ]
