# Generated by Django 2.2.7 on 2019-12-02 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20191128_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bigblock_award',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gold_pin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='goldplus_pin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='platinum_pin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='silver_pin',
        ),
    ]
