# Generated by Django 2.2.5 on 2019-10-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20191002_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='term1',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='term2',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='homeroom',
            field=models.CharField(help_text='Use the dropdown actions at the Student list to move student down a grade', max_length=15, verbose_name='Homeroom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_num',
            field=models.PositiveIntegerField(help_text='This number must be unique as it is used to identify students', unique=True, verbose_name='Student Number'),
        ),
    ]
