# Generated by Django 2.1.1 on 2018-09-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20180630_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
