# Generated by Django 2.2.7 on 2019-12-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20191202_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='isnull_AT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='isnull_FA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='isnull_SC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='isnull_SE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='isnull_term1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='isnull_term2',
            field=models.BooleanField(default=False),
        ),
    ]
