# Generated by Django 2.2.5 on 2019-11-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20191023_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='p_list',
        ),
        migrations.AddField(
            model_name='certificates',
            name='t1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='t2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='athletics',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='fine_arts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='honour',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='service',
            field=models.BooleanField(default=True),
        ),
    ]
