# Generated by Django 2.2.7 on 2019-11-27 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20191031_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_10',
            fields=[
                ('grade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Grade')),
            ],
            bases=('data.grade',),
        ),
        migrations.CreateModel(
            name='Grade_11',
            fields=[
                ('grade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Grade')),
            ],
            bases=('data.grade',),
        ),
        migrations.CreateModel(
            name='Grade_12',
            fields=[
                ('grade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Grade')),
            ],
            bases=('data.grade',),
        ),
        migrations.CreateModel(
            name='Grade_8',
            fields=[
                ('grade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Grade')),
            ],
            bases=('data.grade',),
        ),
        migrations.CreateModel(
            name='Grade_9',
            fields=[
                ('grade_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Grade')),
            ],
            bases=('data.grade',),
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='Grade',
        ),
        migrations.RemoveField(
            model_name='scholar',
            name='Grade',
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='homeroom',
        ),
        migrations.AddField(
            model_name='grade',
            name='AT_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='grade',
            name='FA_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='grade',
            name='SC_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='grade',
            name='SE_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='grade',
            name='_term1_avg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='grade',
            name='_term2_avg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='student',
            name='cur_grade',
            field=models.IntegerField(default=8, verbose_name='current grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='goldplus_pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='homeroom_char',
            field=models.CharField(default='A', max_length=1, verbose_name='Homeroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='silver_pin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
        migrations.DeleteModel(
            name='Certificates',
        ),
        migrations.DeleteModel(
            name='Scholar',
        ),
        migrations.AddField(
            model_name='student',
            name='Grade_10',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Grade_10'),
        ),
        migrations.AddField(
            model_name='student',
            name='Grade_11',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Grade_11'),
        ),
        migrations.AddField(
            model_name='student',
            name='Grade_12',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Grade_12'),
        ),
        migrations.AddField(
            model_name='student',
            name='Grade_8',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Grade_8'),
        ),
        migrations.AddField(
            model_name='student',
            name='Grade_9',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Grade_9'),
        ),
    ]
