# Generated by Django 2.2.7 on 2019-12-06 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20191206_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade_10',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='data.Grade_10'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_11',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='data.Grade_11'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_12',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='data.Grade_12'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_8',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='data.Grade_8'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_9',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='data.Grade_9'),
        ),
    ]
