# Generated by Django 2.1.1 on 2018-11-08 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20181003_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='code',
        ),
        migrations.AlterField(
            model_name='points',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.PointCodes'),
        ),
    ]
