# Generated by Django 2.1.1 on 2018-12-06 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20181204_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.PointCodes'),
        ),
    ]
