# Generated by Django 2.1.5 on 2019-01-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20181205_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlistCutoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade8_t1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade8_t2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade9_t1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade9_t2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade10_t1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade10_t2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade11_t1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade11_t2', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade12_t1', models.DecimalField(decimal_places=3, max_digits=5)),
                ('grade12_t2', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
