# Generated by Django 2.2.8 on 2019-12-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20191214_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last', 'first']},
        ),
        migrations.AddField(
            model_name='grade',
            name='term1_GE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='term2_GE',
            field=models.BooleanField(default=False),
        ),
    ]
