# Generated by Django 2.0.5 on 2018-05-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField()),
                ('start_year', models.SmallIntegerField()),
                ('anecdote', models.SlugField(blank=True, max_length=300)),
                ('SE_total', models.DecimalField(decimal_places=1, max_digits=5)),
                ('AT_total', models.DecimalField(decimal_places=1, max_digits=5)),
                ('FA_total', models.DecimalField(decimal_places=1, max_digits=5)),
                ('SC_total', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30)),
                ('last', models.CharField(max_length=30)),
                ('student_num', models.PositiveIntegerField()),
                ('homeroom', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=1)),
                ('date_added', models.DateField()),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.Student'),
        ),
    ]
