# Generated by Django 2.0.4 on 2018-05-01 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField()),
                ('start_year', models.SmallIntegerField()),
                ('end_year', models.SmallIntegerField()),
                ('anecdote', models.SlugField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term1', models.DecimalField(decimal_places=5, max_digits=7)),
                ('term2', models.DecimalField(decimal_places=5, max_digits=7)),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30)),
                ('last', models.CharField(max_length=30)),
                ('student_num', models.PositiveIntegerField()),
                ('homeroom', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=1)),
                ('date_added', models.DateField()),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.Student'),
        ),
    ]
