# Generated by Django 2.0.4 on 2018-04-20 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_herding', models.DecimalField(decimal_places=1, max_digits=5)),
                ('surgery', models.DecimalField(decimal_places=1, max_digits=5)),
                ('sleeping', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30)),
                ('last', models.CharField(max_length=30)),
                ('student_num', models.PositiveIntegerField()),
                ('homeroom', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.Student'),
        ),
    ]
