# Generated by Django 2.0.4 on 2018-04-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='homeroom',
            field=models.CharField(max_length=3),
        ),
    ]
