# Generated by Django 2.0.4 on 2018-05-01 00:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0002_auto_20180420_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField()),
                ('start_year', models.SmallIntegerField()),
                ('end_year', models.SmallIntegerField()),
                ('anecdote', models.SlugField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term1', models.DecimalField(decimal_places=5, max_digits=7)),
                ('term2', models.DecimalField(decimal_places=5, max_digits=7)),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.Grade')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='Student',
        ),
        migrations.AddField(
            model_name='student',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='grade',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test2.Student'),
        ),
    ]
