# Generated by Django 2.0.5 on 2018-06-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0003_auto_20180619_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='AT_total',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='grade',
            name='FA_total',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='grade',
            name='SC_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='grade',
            name='SE_total',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5),
        ),
    ]
