# Generated by Django 2.1.1 on 2018-10-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0008_auto_20180924_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='AT_total',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='FA_total',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='SC_total',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='SE_total',
        ),
    ]
