# Generated by Django 2.1.2 on 2019-06-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0014_plistcutoff_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plistcutoff',
            old_name='grade10_t1',
            new_name='grade_10_T1',
        ),
        migrations.RenameField(
            model_name='plistcutoff',
            old_name='grade10_t2',
            new_name='grade_10_T2',
        ),
        migrations.RenameField(
            model_name='plistcutoff',
            old_name='grade11_t1',
            new_name='grade_11_T1',
        ),
        migrations.RenameField(
            model_name='plistcutoff',
            old_name='grade11_t2',
            new_name='grade_11_t2',
        ),
        migrations.RenameField(
            model_name='plistcutoff',
            old_name='grade12_t1',
            new_name='grade_12_T1',
        ),
        migrations.RenameField(
            model_name='plistcutoff',
            old_name='grade12_t2',
            new_name='grade_12_T2',
        ),
        migrations.RenameField(
            model_name='plistcutoff',
            old_name='grade8_t1',
            new_name='grade_8_T1',
        ),
        migrations.RenameField(
            model_name='plistcutoff',
            old_name='grade8_t2',
            new_name='grade_8_t2',
        ),
        migrations.RenameField(
            model_name='plistcutoff',
            old_name='grade9_t1',
            new_name='grade_9_T1',
        ),
        migrations.RenameField(
            model_name='plistcutoff',
            old_name='grade9_t2',
            new_name='grade_9_T2',
        ),
    ]
