# Generated by Django 2.1.2 on 2019-06-29 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0016_auto_20190627_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plistcutoff',
            options={'verbose_name': 'Principal List Cutoff', 'verbose_name_plural': 'Principal List Cutoffs'},
        ),
    ]
