# Generated by Django 2.2.3 on 2019-07-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0018_auto_20190710_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_added',
            field=models.DateField(blank=True, null=True, verbose_name='Date of entry into Point Grey'),
        ),
    ]
