# Generated by Django 2.2.3 on 2019-07-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0019_auto_20190710_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_added',
        ),
        migrations.AddField(
            model_name='student',
            name='grad_year',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
